# Generated by Django 4.1.4 on 2022-12-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0002_user_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default="whatever", max_length=50),
        ),
    ]
