# Generated by Django 4.1.4 on 2023-01-04 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0003_user_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
    ]
