# Generated by Django 4.1.4 on 2023-01-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0004_remove_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
