# Generated by Django 4.1.4 on 2022-12-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                ("shop_name", models.TextField(max_length=50)),
                (
                    "mobile_number",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("password", models.TextField(max_length=50)),
                ("pincode", models.IntegerField(max_length=6)),
                ("otp", models.IntegerField(max_length=4)),
                ("is_verified", models.BooleanField(default=False)),
            ],
        ),
    ]
