# Generated by Django 4.1.4 on 2022-12-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="otp",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="pincode",
            field=models.IntegerField(),
        ),
    ]
