# Generated by Django 4.1.4 on 2023-01-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_vendor_otp_alter_vendor_pincode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="otp",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
