# Generated by Django 4.1.4 on 2023-01-03 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_productcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "product_name",
                    models.TextField(max_length=50, primary_key=True, serialize=False),
                ),
                ("product_price", models.IntegerField()),
                ("product_details", models.TextField(max_length=100)),
                ("product_image", models.ImageField(upload_to="products")),
                (
                    "product_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.productcategory",
                    ),
                ),
                (
                    "shop_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.vendor"
                    ),
                ),
            ],
        ),
    ]
