# Generated by Django 4.1.4 on 2023-01-03 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="shop_name",
            new_name="shop_number",
        ),
    ]
