# Generated by Django 4.1.4 on 2023-01-03 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_rename_shop_number_product_shop_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="shop_name",
            new_name="shop",
        ),
    ]
