# Generated by Django 4.1.4 on 2023-01-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_rename_shop_name_product_shop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=models.ImageField(upload_to="products/"),
        ),
    ]
