# Generated by Django 4.1.4 on 2023-01-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_alter_product_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="shop_image",
            field=models.ImageField(blank=True, null=True, upload_to="shops/"),
        ),
    ]
